### ISSUE TITLE
HTML Tidy

### ISSUE THREAD

**Issue by thorade** [DLR-SR/AdvancedNoise#19]
HTML Tidy gives some minor warnings, 
search for AdvancedNoise here:
https://build.openmodelica.org/Documentation/tidy.filtered

**Comment by tobolar** [comment]
@thorade I have tried to fix all the format issues. It would be great if you could perform your check again and update your document, if necessary.

**Comment by thorade** [comment]
I ran a test locally with buildingspy and HTML Tidy, it still reports a lot of warnings that probably have to be fixed manually (or use regex and use filename as summar/alt?):
* Warning: <table> lacks "summary" attribute
* Warning: <img> lacks "alt" attribute

And a lot of Infos that can be fixed using search and replace:
* Info: value for attribute "border" missing quote marks
* Info: value for attribute "cellspacing" missing quote marks
* Info: value for attribute "cellpadding" missing quote marks
* Info: value for attribute "border" missing quote marks

As far as I can see, these cover all types or warnings and infos.

**Comment by tobolar** [comment]
>  `<table>` lacks "summary" attribute

Do you rather mean "caption" as described in Modelica.UsersGuide.Conventions.Documentation.Format.Tables?

```
<table border="1" cellspacing="0" cellpadding="2">
  <caption align="bottom">Caption starts with a capital letter</caption>
  ...
```

**Comment by thorade** [comment]
No, tidy complains about the summary attribute:
`<table border="1" cellspacing="0" cellpadding="2" summary="a short summary of what the table shows">`
This will not change how the table looks, just like the image alt attribute.

**Comment by tobolar** [comment]
In this case I would rather comply with the abovementioned convention recommendation in Modelica.UsersGuide.Conventions.Documentation.Format.Tables. Maybe its a lack there in the MSL, but I haven't found that attribute in any of MSL documentation.

Maybe you could open an issue in MSL concerning "summary" vs. "caption"?
