### ISSUE TITLE
Initialization of AdvancedNoise.Examples.TimeBasedNoise

### ISSUE THREAD

**Issue by tbeu** [DLR-SR/AdvancedNoise#20]
Since AdvancedNoise.Sources.TimeBasedNoise with useAutomaticLocalSeed=false calls impureRandomInteger in when initial(), a new value is assigned to localSeed for each event iteration of the initialization, leading to new event steps and so on. It is not clear how this is supposed to terminate with consistent initial conditions. It might be tool issue with handling impure functions at initialization time, but any help is appreciated. Thank you!

**Comment by akloeckner** [comment]
According to my understanding, the `when`-clause is only executed once per event iteration. The consistent `localSeed` is thus the one from the first and only call to `impureRandomInteger`, as would be the case, e.g., for the `reinit` operator. 

This would be different from an `if`-clause, which would be evaluated in each and every loop (or step) of the event iteration.

Compare https://www.modelica.org/documents/ModelicaSpec33.pdf, Sections 8.3.4-8.3.6.

**Comment by tbeu** [comment]
There are tools that execute the when clause more than once.

I checked why initialization with MSL Noise  of v3.2.2 works but AdvancedNoise fails and rediscovered my own issue modelica/Modelica#1917 that was fixed by @MartinOtter with https://github.com/modelica/Modelica/issues/1917#issuecomment-272681226.

I'd propose to modify the localSeed the same way as the MSL Noise, that is making localSeed a fixed-false parameter with an initial equation
```diff
 AdvancedNoise 1.0.0/Sources/TimeBasedNoise.mo | 6 ++----
 1 file changed, 2 insertions(+), 4 deletions(-)

diff --git a/AdvancedNoise 1.0.0/Sources/TimeBasedNoise.mo b/AdvancedNoise 1.0.0/Sources/TimeBasedNoise.mo
index 5d934ab..b4b00e4 100644
--- a/AdvancedNoise 1.0.0/Sources/TimeBasedNoise.mo	
+++ b/AdvancedNoise 1.0.0/Sources/TimeBasedNoise.mo	
@@ -115,11 +115,9 @@ block TimeBasedNoise
       annotation(Dialog(tab="Advanced",group = "Initialization",enable=enableNoise and not useAutomaticLocalSeed));
 
   // Generate the actually used local seed
-  discrete Integer localSeed "The actual localSeed";
-equation
-  when initial() then
+  final parameter Integer localSeed(fixed = false) "The actual localSeed";
+initial equation
     localSeed = if useAutomaticLocalSeed then impureRandomInteger(globalSeed.id_impure) else fixedLocalSeed;
-  end when;
 
 public
     parameter Modelica.SIunits.Time startTime = 0.0
```
Do you think this would be a sound contribution?

**Comment by akloeckner** [comment]
I don't see any downside. I even consider it more elegant. But I could be missing something. Maybe @fvanderlinden, @tobolar or @MartinOtter can cross-check?

**Comment by tbeu** [comment]
If you check the comments and revision history of modelica/Modelica#1917 you will see that the proposed solution was not found at once but was developed with some evolution when tested across different tools. So it should be safe to apply same idea.

**Comment by tbeu** [comment]
Any news on this?

**Comment by tobolar** [comment]
I have checked the https://github.com/modelica/Modelica/issues/1917 and it seem to me to be fine.

**Comment by tbeu** [comment]
Any news on this when the fix can be expected?

**Comment by tbeu** [comment]
Any news on this when the fix can be expected?

**Comment by tobolar** [comment]
I could proceed after Modelica Conference, i.e. by end of Mai.

**Comment by tobolar** [comment]
@tbeu please check if the solution works for you now.

**Comment by tbeu** [comment]
Thank you, @tobolar! Finally works in SimulationX.
